#YASHWANTH K
KSIT

1KS18CS121

#TOPIC : "PREDICTING TYPE OF GLASS"


Type of glass: (class attribute)

-- 1 building windows float processed

-- 2 building windows non float processed 

-- 3 vehicle windows float processed

-- 4 vehicle windows non float processed (none in this database)

-- 5 containers

-- 6 tableware

-- 7 headlamps


#Data Preprocessing

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/Projects/GlassDetails.csv')
dataset

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [4]:
dataset.describe()

RI          Na          Mg  ...          Ba          Fe        Type
count  214.000000  214.000000  214.000000  ...  214.000000  214.000000  214.000000
mean     1.518365   13.407850    2.684533  ...    0.175047    0.057009    2.780374
std      0.003037    0.816604    1.442408  ...    0.497219    0.097439    2.103739
min      1.511150   10.730000    0.000000  ...    0.000000    0.000000    1.000000
25%      1.516523   12.907500    2.115000  ...    0.000000    0.000000    1.000000
50%      1.517680   13.300000    3.480000  ...    0.000000    0.000000    2.000000
75%      1.519157   13.825000    3.600000  ...    0.000000    0.100000    3.000000
max      1.533930   17.380000    4.490000  ...    3.150000    0.510000    7.000000

[8 rows x 10 columns]

##Seperating features and target

->Here feature values are the values model will use to predict the answer 

->Target value is the value which model will predict...

In [5]:
#Collecting all coumn values from dataset except target value(that is last column) 

X = dataset.iloc[:,:-1].values


X

array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  8.44   ,  1.64   ,  0.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  8.48   ,  1.57   ,  0.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  8.62   ,  1.67   ,  0.     ]])

In [6]:
#Here we are taking last column as Target column 
y = dataset.iloc[:,-1].values
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

##Splitting dataset to train and test
splitting train and test values

75% of values to train and 25% to test

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [8]:
print(len(X_test))
X_train

54


array([[ 1.51753, 12.57   ,  3.47   , ...,  8.55   ,  0.     ,  0.06   ],
       [ 1.51969, 12.64   ,  0.     , ..., 11.53   ,  0.     ,  0.     ],
       [ 1.52667, 13.99   ,  3.7    , ...,  9.82   ,  0.     ,  0.1    ],
       ...,
       [ 1.51514, 14.85   ,  0.     , ...,  8.39   ,  0.56   ,  0.     ],
       [ 1.51711, 12.89   ,  3.62   , ...,  8.11   ,  0.     ,  0.     ],
       [ 1.51764, 12.98   ,  3.54   , ...,  8.53   ,  0.     ,  0.     ]])

##Scaling

Here we are Standardising the data to the range -3 to +3 by using StandardScaler

In [9]:
sc = StandardScaler()

In [10]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
X_train

array([[-0.26615426, -0.96121326,  0.55107934, ..., -0.28352608,
        -0.34690055,  0.10997887],
       [ 0.41444442, -0.87894528, -1.88432025, ...,  1.7127119 ,
        -0.34690055, -0.5337999 ],
       [ 2.61378642,  0.70765158,  0.71250352, ...,  0.56721963,
        -0.34690055,  0.53916472],
       ...,
       [-1.01922408,  1.71837254, -1.88432025, ..., -0.39070664,
         0.74332356, -0.5337999 ],
       [-0.39849289, -0.58513104,  0.65635598, ..., -0.57827263,
        -0.34690055, -0.5337999 ],
       [-0.23149414, -0.47935792,  0.60020844, ..., -0.29692365,
        -0.34690055, -0.5337999 ]])

In [12]:
#Model will give response with numbers 1 to 7, So we are converting that numbers to actual values by using this function.
def values(arg):
  dict={
      1:"building windows float processed",
      2:"building windows non-float processed",
      3:"vehicle windows floatprocessed",
      4:"vehiclewindowsnonfloatprocessed",
      5:"containers",
      6:"tableware",
      7:"headlamps" 
      }
  return dict.get(arg)

#Classification



##Logistic Regression

In [13]:
lcla=LogisticRegression()

In [14]:
lcla.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
lpred=lcla.predict(sc.transform([[1.52101,13.64,4.49,1.1,71.78,0.06,8.75,0,0]]))
lpred

array([1])

In [16]:
lpred=lcla.predict(X_test)

In [17]:
for i in range(len(y_test)):
  print("predicted value :",lpred[i],"\tActual value :",y_test[i],",",values(y_test[i]))

predicted value : 2 	Actual value : 1 , building windows float processed
predicted value : 2 	Actual value : 1 , building windows float processed
predicted value : 1 	Actual value : 2 , building windows non-float processed
predicted value : 1 	Actual value : 1 , building windows float processed
predicted value : 1 	Actual value : 1 , building windows float processed
predicted value : 2 	Actual value : 1 , building windows float processed
predicted value : 1 	Actual value : 1 , building windows float processed
predicted value : 1 	Actual value : 1 , building windows float processed
predicted value : 2 	Actual value : 1 , building windows float processed
predicted value : 2 	Actual value : 2 , building windows non-float processed
predicted value : 1 	Actual value : 1 , building windows float processed
predicted value : 6 	Actual value : 6 , tableware
predicted value : 7 	Actual value : 7 , headlamps
predicted value : 1 	Actual value : 1 , building windows float processed
predicted value 

In [18]:
lac=accuracy_score(y_test,lpred)

lac

0.6481481481481481

##K-Nearest Neighbours

In [19]:
kcla=KNeighborsClassifier()

In [20]:
kcla.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [21]:
kpred = kcla.predict(X_test) 
print(len(kpred))

54


In [22]:
for j in range(len(y_test)):
  print("predicted value :",kpred[j],"\tActual value :",y_test[j])

predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 6 	Actual value : 6
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 2 	Actual value : 5
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 5 	Actual value : 2
predicted value : 7 	Actual value : 7
predicted va

In [23]:
kac=accuracy_score(y_test,kpred)

kac

0.6666666666666666

##Decision tree

In [24]:
dcla = DecisionTreeClassifier()

In [25]:
dcla.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [26]:
dpred = dcla.predict(X_test)

In [27]:
for i in range(len(y_test)):
  print("predicted value :",dpred[i],"\tActual value :",y_test[i])

predicted value : 2 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 2
predicted value : 2 	Actual value : 1
predicted value : 6 	Actual value : 6
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 3 	Actual value : 2
predicted value : 5 	Actual value : 5
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 6 	Actual value : 2
predicted value : 7 	Actual value : 7
predicted va

In [28]:
dac=accuracy_score(y_test,dpred)

dac

0.6481481481481481

##Random forest

In [29]:
rcla= RandomForestClassifier(n_estimators=220)

In [30]:
rcla.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=220,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [31]:
rpred = rcla.predict(X_test)

In [32]:
for i in range(len(y_test)):
  print("predicted value :",rpred[i],"\tActual value :",y_test[i])

predicted value : 2 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 6 	Actual value : 6
predicted value : 7 	Actual value : 7
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 5 	Actual value : 5
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 6 	Actual value : 2
predicted value : 7 	Actual value : 7
predicted va

In [33]:
rac=accuracy_score(y_test,rpred)

rac

0.8333333333333334

##Support Vector Machine

In [34]:
#scla = SVC(kernel='linear')
scla = SVC()

In [35]:
scla.fit(X_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [36]:
spred = scla.predict(X_test)

In [37]:
for i in range(len(y_test)):
  print("predicted value :",spred[i],"\tActual value :",y_test[i])

predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 1 	Actual value : 1
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 6 	Actual value : 6
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 1
predicted value : 1 	Actual value : 2
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 5 	Actual value : 5
predicted value : 2 	Actual value : 2
predicted value : 1 	Actual value : 1
predicted value : 7 	Actual value : 7
predicted value : 2 	Actual value : 2
predicted value : 6 	Actual value : 2
predicted value : 7 	Actual value : 7
predicted va

In [38]:
sac=accuracy_score(y_test,spred)

sac

0.7592592592592593

#Comparing 

In [39]:
print("Logistic Regression  :",lac,"\nK-Nearest Neighbours :",kac,"\nDecision tree    :",dac,
      "\nRandom forest        :",rac,"\nSVM    \t\t     :",sac)

Logistic Regression  : 0.6481481481481481 
K-Nearest Neighbours : 0.6666666666666666 
Decision tree    : 0.6481481481481481 
Random forest        : 0.8333333333333334 
SVM    		     : 0.7592592592592593


#By taking user input predicting values using Random Forest Algorithm

In [40]:
print("Enter values RI: refractive index Na: Sodium Mg: Magnesium Al: Aluminum Si: Silicon K: Potassium Ca: Calcium Ba: Barium Fe: Iron")
print("\n For Example [1.52101, 13.64, 4.49, 1.1, 71.78, 0.06, 8.75, 0,0]\n ")
RI = input('RI:')
Na = input('Na:')
Mg = input('Mg:')
Al = input('Al:')
Si = input('Si:')
K = input('K:')
Ca = input('Ca:')
Ba = input('Ba:')
Fe = input('Fe:')

Enter values RI: refractive index Na: Sodium Mg: Magnesium Al: Aluminum Si: Silicon K: Potassium Ca: Calcium Ba: Barium Fe: Iron

 For Example [1.52101, 13.64, 4.49, 1.1, 71.78, 0.06, 8.75, 0,0]
 
RI:1.5
Na:13
Mg:4
Al:1.1
Si:71.78
K:0.06
Ca:8.75
Ba:0
Fe:0


In [41]:
rpred=rcla.predict(sc.transform([[RI,Na,Mg,Al,Si,K,Ca,Ba,Fe]]))
values(rpred[0])

'building windows float processed'